name: chat_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  rive: ^0.13.20
  googleapis_auth: ^1.6.0
  json_annotation: ^4.9.0
  firebase_auth: ^5.4.0
  firebase_core: ^3.10.0
  google_sign_in: ^6.2.2
  oauth2_client: ^3.3.0
  googleapis: ^13.2.0
  cloud_firestore: ^5.6.2
  provider: ^6.1.2
  firebase_database: ^11.3.0
  firebase_messaging: ^15.2.0
  fluttertoast: ^8.2.10
  flutter_local_notifications: ^18.0.1
#  flutter_launcher_icons: ^0.14.3
  http: ^1.2.2
  firebase_admin: ^0.3.0
  firebase_dynamic_links: ^6.1.1
  share_plus: ^10.1.4
  image_picker: ^1.1.2
  firebase_storage: ^12.4.1
  zego_uikit_prebuilt_call: ^4.16.21
  zego_uikit_prebuilt_video_conference: ^2.9.8
  intl: ^0.19.0

#flutter_launcher_icons:
#  android: "ic_launcher"
#  ios: true
#  remove_alpha_ios: true
#  image_path: "assets/icon/chat_app_icon.png"
#  min_sdk_android: 24
#  adaptive_icon_foreground: "assets/icon/chat_app_icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  change_app_package_name: ^1.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/logos/
    - assets/icon/
    - assets/images/
