// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBay0NWLKsQg-FUteWnJK3LYou8WRWgk4s',
    appId: '1:796808834155:web:ef87e21fa8bf310585152e',
    messagingSenderId: '796808834155',
    projectId: 'aimit-151',
    authDomain: 'aimit-151.firebaseapp.com',
    storageBucket: 'aimit-151.appspot.com',
    measurementId: 'G-Z5GY6YLSCK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5SZrdHqJFPa4RP-Jl-M99NXQDlUCn5U8',
    appId: '1:796808834155:android:ded9fd27f0d40bfd85152e',
    messagingSenderId: '796808834155',
    projectId: 'aimit-151',
    storageBucket: 'aimit-151.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXjBb0yRu88CqZpQlNOf-0odopsFMdWWQ',
    appId: '1:796808834155:ios:b455b7ee8d66b86585152e',
    messagingSenderId: '796808834155',
    projectId: 'aimit-151',
    storageBucket: 'aimit-151.appspot.com',
    androidClientId: '796808834155-6jljqit6ra5ak9k7e2uliu6bbk3vmg5a.apps.googleusercontent.com',
    iosClientId: '796808834155-ahed0ruc8qnm2o11anna8ql2i0kpsg2s.apps.googleusercontent.com',
    iosBundleId: 'com.communicates.conversations',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXjBb0yRu88CqZpQlNOf-0odopsFMdWWQ',
    appId: '1:796808834155:ios:f9b4480c5e2e6d3985152e',
    messagingSenderId: '796808834155',
    projectId: 'aimit-151',
    storageBucket: 'aimit-151.appspot.com',
    androidClientId: '796808834155-6jljqit6ra5ak9k7e2uliu6bbk3vmg5a.apps.googleusercontent.com',
    iosClientId: '796808834155-eia9ut6a5s315i0maactakpmp8dv2p4v.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDssHsWnKMV5pVriHSaL8vaPzIYYnp3KsE',
    appId: '1:796808834155:web:053a8fb51d3e21dd85152e',
    messagingSenderId: '796808834155',
    projectId: 'aimit-151',
    authDomain: 'aimit-151.firebaseapp.com',
    storageBucket: 'aimit-151.appspot.com',
    measurementId: 'G-6E435V4BXF',
  );

}